// NOTE: This file is auto-generated by React Cosmos.
import type { RendererConfig, UserModuleWrappers } from 'react-cosmos-core';

import * as fixture0 from './src/components/ui/alert-dialog.fixture';
import * as fixture1 from './src/components/ui/aspect-ratio.fixture';
import * as fixture2 from './src/components/ui/avatar.fixture';
import * as fixture3 from './src/components/ui/badge.fixture';
import * as fixture4 from './src/components/ui/button.fixture';
import * as fixture5 from './src/components/ui/card.fixture';
import * as fixture6 from './src/components/ui/code-block.fixture';
import * as fixture7 from './src/components/ui/command.fixture';
import * as fixture8 from './src/components/ui/dialog.fixture';
import * as fixture9 from './src/components/ui/drawer.fixture';
import * as fixture10 from './src/components/ui/dropdown-menu.fixture';
import * as fixture11 from './src/components/ui/field.fixture';
import * as fixture12 from './src/components/ui/input-group.fixture';
import * as fixture13 from './src/components/ui/input.fixture';
import * as fixture14 from './src/components/ui/kbd.fixture';
import * as fixture15 from './src/components/ui/label.fixture';
import * as fixture16 from './src/components/ui/marquee.fixture';
import * as fixture17 from './src/components/ui/popover.fixture';
import * as fixture18 from './src/components/ui/scroll-area.fixture';
import * as fixture19 from './src/components/ui/segment-group.fixture';
import * as fixture20 from './src/components/ui/select.fixture';
import * as fixture21 from './src/components/ui/separator.fixture';
import * as fixture22 from './src/components/ui/sheet.fixture';
import * as fixture23 from './src/components/ui/sidebar.fixture';
import * as fixture24 from './src/components/ui/skeleton.fixture';
import * as fixture25 from './src/components/ui/sonner.fixture';
import * as fixture26 from './src/components/ui/spinner.fixture';
import * as fixture27 from './src/components/ui/switch.fixture';
import * as fixture28 from './src/components/ui/table.fixture';
import * as fixture29 from './src/components/ui/tabs.fixture';
import * as fixture30 from './src/components/ui/textarea.fixture';
import * as fixture31 from './src/components/ui/tip.fixture';
import * as fixture32 from './src/components/ui/tooltip.fixture';
import * as fixture33 from './src/components/ui/tree-view.fixture';
import * as fixture34 from './src/components/unsubscribe-comment-reply-form.fixture';
import * as fixture35 from './src/components/unsubscribe-error.fixture';

import * as decorator0 from './src/components/cosmos.decorator';

export const rendererConfig: RendererConfig = {
  webSocketUrl: null,
  rendererUrl: '/cosmos/<fixture>.html',
};

const fixtures = {
  'src/components/ui/alert-dialog.fixture.tsx': { module: fixture0 },
  'src/components/ui/aspect-ratio.fixture.tsx': { module: fixture1 },
  'src/components/ui/avatar.fixture.tsx': { module: fixture2 },
  'src/components/ui/badge.fixture.tsx': { module: fixture3 },
  'src/components/ui/button.fixture.tsx': { module: fixture4 },
  'src/components/ui/card.fixture.tsx': { module: fixture5 },
  'src/components/ui/code-block.fixture.tsx': { module: fixture6 },
  'src/components/ui/command.fixture.tsx': { module: fixture7 },
  'src/components/ui/dialog.fixture.tsx': { module: fixture8 },
  'src/components/ui/drawer.fixture.tsx': { module: fixture9 },
  'src/components/ui/dropdown-menu.fixture.tsx': { module: fixture10 },
  'src/components/ui/field.fixture.tsx': { module: fixture11 },
  'src/components/ui/input-group.fixture.tsx': { module: fixture12 },
  'src/components/ui/input.fixture.tsx': { module: fixture13 },
  'src/components/ui/kbd.fixture.tsx': { module: fixture14 },
  'src/components/ui/label.fixture.tsx': { module: fixture15 },
  'src/components/ui/marquee.fixture.tsx': { module: fixture16 },
  'src/components/ui/popover.fixture.tsx': { module: fixture17 },
  'src/components/ui/scroll-area.fixture.tsx': { module: fixture18 },
  'src/components/ui/segment-group.fixture.tsx': { module: fixture19 },
  'src/components/ui/select.fixture.tsx': { module: fixture20 },
  'src/components/ui/separator.fixture.tsx': { module: fixture21 },
  'src/components/ui/sheet.fixture.tsx': { module: fixture22 },
  'src/components/ui/sidebar.fixture.tsx': { module: fixture23 },
  'src/components/ui/skeleton.fixture.tsx': { module: fixture24 },
  'src/components/ui/sonner.fixture.tsx': { module: fixture25 },
  'src/components/ui/spinner.fixture.tsx': { module: fixture26 },
  'src/components/ui/switch.fixture.tsx': { module: fixture27 },
  'src/components/ui/table.fixture.tsx': { module: fixture28 },
  'src/components/ui/tabs.fixture.tsx': { module: fixture29 },
  'src/components/ui/textarea.fixture.tsx': { module: fixture30 },
  'src/components/ui/tip.fixture.tsx': { module: fixture31 },
  'src/components/ui/tooltip.fixture.tsx': { module: fixture32 },
  'src/components/ui/tree-view.fixture.tsx': { module: fixture33 },
  'src/components/unsubscribe-comment-reply-form.fixture.tsx': { module: fixture34 },
  'src/components/unsubscribe-error.fixture.tsx': { module: fixture35 },
};

const decorators = {
  'src/components/cosmos.decorator.tsx': { module: decorator0 },
};

export const moduleWrappers: UserModuleWrappers = {
  lazy: false,
  fixtures,
  decorators,
};